### ISSUE TITLE
Add support for reserving subdomains

### ISSUE THREAD

**Issue by amalshaji** [amalshaji/beaver#2]
Update the server config to add reserved endpoints to users schema

```yaml
users:
  - identifier: foo@bar.com
    secretkey: ThisIsASecret
	reserved_subdomains:
		- foo-dev-1
		- foo-dev-2
  - identifier: max@xam.com
    secretkey: ThisIsASecret@2
```

When `foo-dev-1` or `foo-dev-2` is requested by any user other than `foo@bar.com`, the server should reject the request.
